### ISSUE TITLE
[16]  purchase_stock_account_invoice_pending instalable = false

### ISSUE THREAD

**Issue by Gelojr** [Tecnativa/extra-addons#5]
Hola @sergio-teruel ,

El módulo está con el parámetro https://github.com/Tecnativa/extra-addons/blob/c8c3e40de8c2abdf31e1e6d902baec85c7b78b65/purchase_stock_account_invoice_pending/__manifest__.py#L21

¿Puedes por favor ponerlo como  "installable": True para poder testearlo?

Gracias y un saludo

@moduon MT-3585

**Comment by sergio-teruel** [comment]
Done!

**Comment by EmilioPascual** [comment]
Gracias!
