### ISSUE TITLE
[16]  sale_tier_validation_security_price instalable = false 

### ISSUE THREAD

**Issue by Gelojr** [Tecnativa/extra-addons#6]
Hola @sergio-teruel ,
El módulo está con el parámetro
https://github.com/Tecnativa/extra-addons/blob/c8c3e40de8c2abdf31e1e6d902baec85c7b78b65/sale_tier_validation_security_price/__manifest__.py#L13

¿Puedes por favor ponerlo como "installable": True para poder testearlo?

Gracias y un saludo

@moduon MT-3026

**Comment by sergio-teruel** [comment]
Done

**Comment by Gelojr** [comment]
Thanks @sergio-teruel
