### ISSUE TITLE
[16.0] sale_tier_validation_security_price

### ISSUE THREAD

**Issue by Shide** [Tecnativa/extra-addons#9]
Buenas @sergio-teruel,
estoy viendo que no se puede Rechazar una validación si el módulo de **sale_tier_validation_security_price** está instalado. Siempre confirma el pedido.

Lo que he hecho:
Archivo la definición de nivel "Pedido de venta con precio mínimo excedido" y creo una nueva que siempre devuelva True (para no complicarme). Así simulo que no hay un problema con el Precio pero sí con otra cosa.
Voy a un pedido, solicito validación y luego la Rechazo.

Este es el código en el que veo problemas: https://github.com/Tecnativa/extra-addons/blob/16.0/sale_tier_validation_security_price/models/sale_order.py#L24-L42

El código nunca llega a hacer ningún `super()`, además de que aunque no exista el ref("sale_tier_validation_security_price.sale_order_minimal_price_tier"), confirma el pedido igualmente.

Creo que debería haber un control adicional por si no se cumplen las condiciones del security price, para que salte al super().

Quizás algo parecido a ésto (muevo el IF del ref al principio y al final un super())
```python
    def _rejected_tier(self, tiers=False):
        sec_price_tier_exists = tiers and self.env.ref(
            "sale_tier_validation_security_price.sale_order_minimal_price_tier"
        ) in tiers.mapped("definition_id")

        if not (sec_price_tier_exists and not self.need_validation and tiers):
            return super()._rejected_tier(tiers=tiers)

        ctx = self.env.context.copy()
        ctx.update({"security_price_tier_validation": True})
        lines_to_reject = self.order_line.filtered("security_price_warning")
        lines_to_reject.action_security_price_rejected()
        self.with_context(tier_action_rejected=True)._validate_tier(tiers)
        tier_reviews = tiers | self.review_ids
        if not tier_reviews.filtered(lambda r: r.status == "pending"):
            self.filtered(lambda s: s.state not in ["done", "cancel"]).with_context(
                ctx
            ).action_confirm()
```

O igual es que no estoy entendiendo bien el funcionamiento del módulo, porque luego leo este [help](https://github.com/Tecnativa/extra-addons/blob/16.0/sale_tier_validation_security_price/models/sale_order.py#L45-L49) y ya no se si siempre se confirma el pedido si hay un Security Price Tier establecido.

No obstante, el comportamiento del Rechazar, creo que debería mantenerse (o al menos no confirmar el pedido)

Si me puedes explicar si es el funcionamiento adecuado, te lo agradecería.

Un saludo!

MT-6238 @moduon

**Comment by sergio-teruel** [comment]
Hola @Shide 

Este es un módulo custom.

¿Puedes comentarlo y que nos abra un ticket de soporte?

**Comment by Shide** [comment]
Por supuesto.

Muchas gracias
